# Generated by Django 3.2.8 on 2021-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cakes',
            name='time',
            field=models.TimeField(max_length=50),
        ),
        migrations.AddField(
            model_name='cakes',
            name='cake_Categories',
            field=models.ManyToManyField(related_name='cakes', to='cakes.CakeCategories'),
        ),
    ]
